Use check on condition number rather than smallest eigenvalue
FEniCS/basix pull request #568
Opened 2022-07-21 09:15 UTC by mscroggs

2022-07-21 09:51 UTC, garth-wells commented on cpp/basix/math.cpp
> +  std::vector<double> work(4 * n);
It would be better to requires the caller to pass in these work buffers.

2022-07-21 10:03 UTC, garth-wells requested changes
What speed-up does the change give?

2022-07-21 10:03 UTC, garth-wells commented on cpp/basix/math.h
> +/// For a square matrix A, compute the norm of A multiplied by the reciprocal of
```suggestion
/// For a square matrix A, compute the norm of A multiplied by the (estimated) reciprocal of
```

2022-07-21 10:03 UTC, garth-wells commented on cpp/basix/math.h
> +/// For a square matrix A, compute the norm of A multiplied by the reciprocal of
Which norm?

2022-07-21 10:03 UTC, garth-wells commented on cpp/basix/precompute.cpp
> +  const double rcond_matrix = math::rcond(
Need a check here that the storage of `matrix` is contiguous, and check that it is square.

2022-07-25 10:38 UTC, mscroggs commented
Closing this as #572 is a much better option

2022-07-25 10:38 UTC, closed without merging