Add install instructions for editable Python installation
FEniCS/basix pull request #721
Opened 2023-10-27 09:54 UTC by jorgensd

Tested with:
```docker
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ARG TARGET_PLATFORM
RUN apt-get update && \
    apt-get install -y software-properties-common
RUN apt-get install -y git \
    cmake \
    gcc \
    g++ \
    ninja-build \
    libopenblas-dev \ 
    liblapack-dev
ENV DEB_PYTHON_INSTALL_LAYOUT=deb_system
RUN apt-get install -y python3-pip
RUN python3 -m pip install -U setuptools pip
RUN python3 -m pip install git+https://github.com/FEniCS/ufl.git

ENV CMAKE_BUILD_PARALLEL_LEVEL 2
WORKDIR /src
RUN git clone --branch=dokken/basix-install-instructions --single-branch https://github.com/FEniCS/basix.git
WORKDIR /src/basix
RUN cmake -G Ninja -B build-dir -DCMAKE_BUILD_TYPE=Debug -S cpp/ && \
    cmake --build build-dir && \ 
    cmake --install build-dir

WORKDIR /src/basix/python
RUN python3 -m pip -v install -r build-requirements.txt
RUN python3 -m pip -v install --config-settings=build-dir="build" --config-settings=cmake.build-type="Debug" --no-build-isolation -e .

WORKDIR /tmp
RUN python3 -c "import basix"
```
and
```python
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ARG TARGET_PLATFORM
RUN apt-get update && \
    apt-get install -y software-properties-common
RUN apt-get install -y git \
    cmake \
    gcc \
    g++ \
    ninja-build \
    libopenblas-dev \ 
    liblapack-dev
ENV DEB_PYTHON_INSTALL_LAYOUT=deb_system
RUN apt-get install -y python3-pip
RUN python3 -m pip install -U setuptools pip
RUN python3 -m pip install git+https://github.com/FEniCS/ufl.git

ENV CMAKE_BUILD_PARALLEL_LEVEL 2
WORKDIR /src
RUN git clone --branch=dokken/basix-install-instructions --single-branch https://github.com/FEniCS/basix.git
WORKDIR /src/basix
RUN cmake -G Ninja -B build-dir -DCMAKE_BUILD_TYPE=Debug -S cpp/ && \
    cmake --build build-dir && \ 
    cmake --install build-dir

WORKDIR /src/basix
RUN python3 -m pip -v install -r build-requirements.txt
RUN python3 -m pip -v install --config-settings=build-dir="build" --config-settings=cmake.build-type="Debug" --no-build-isolation -e .

WORKDIR /tmp
RUN python3 -c "import basix"
```
Resolves #719

2023-10-27 09:57 UTC, jhale commented on python/README.rst
> +This document explains how to install the Basix Python interface. Note that
I would add a note along the lines that regular users should use the top-level install.

2023-10-27 10:58 UTC, jorgensd commented on python/README.rst
> +`--no-build-isolation` flag to `pip install`.
```suggestion
This document explains how to install the Basix Python interface, given that the C++ interface has been built.
This is meant for development purposes, and regular users should use the top-level install instructions.
```
What do you think @jhale ?

2023-10-27 11:24 UTC, garth-wells reviewed
See earlier PR - #720.

2023-10-27 12:21 UTC, jhale commented
I think this PR is a little more complete than #720

2023-10-27 12:58 UTC, francesco-ballarin commented
As user, I struggle to understand`*` why build isolation is required with editable installs, but not with standard one. Maybe the reason for this is worth mentioning in the README?

`*` I do understand https://github.com/FEniCS/dolfinx/pull/2707 instead, in the sense that with build isolation even the standard install would fail to locate `mpi4py` and `petsc4py`.

2023-10-27 13:41 UTC, garth-wells commented
> I think this PR is a little more complete than #720

It has too much text. Too much to read and too much that can go out of date. The instructions are for developers, who can do a bit of work themselves.

2023-10-27 14:01 UTC, jorgensd commented
> > I think this PR is a little more complete than #720
> 
> It has too much text. Too much to read and too much that can go out of date. The instructions are for developers, who can do a bit of work themselves.

I dont this this is fair. It is far from trivial to get this to work. The other PR doesn’t even have valid instructions, as it is missing pins and build dependencies

2023-10-27 14:19 UTC, jorgensd commented
> As user, I struggle to understand`*` why build isolation is required with editable installs, but not with standard ones. Maybe the reason for this is worth mentioning in the README?
> 
> `*` I do understand [FEniCS/dolfinx#2707](https://github.com/FEniCS/dolfinx/pull/2707) instead, in the sense that with build isolation even the standard install would fail to locate `mpi4py` and `petsc4py`.

I'm not sure what the cause of the issue is, but if you don't use build-isolation, you get the following error when import basix:
``bash
 > [14/14] RUN python3 -c "import basix":                                                                                                                                                                      
0.408 <frozen importlib._bootstrap>:241: RuntimeWarning: nanobind: type 'LatticeType' was already registered!                                                                                                  
0.408                                                                                                                                                                                                          
0.409 <frozen importlib._bootstrap>:241: RuntimeWarning: nanobind: type 'LatticeSimplexMethod' was already registered!
0.409 
0.410 <frozen importlib._bootstrap>:241: RuntimeWarning: nanobind: type 'PolynomialType' was already registered!
0.410 
0.410 <frozen importlib._bootstrap>:241: RuntimeWarning: nanobind: type 'MapType' was already registered!
0.410 
0.410 <frozen importlib._bootstrap>:241: RuntimeWarning: nanobind: type 'SobolevSpace' was already registered!
0.410 
0.410 <frozen importlib._bootstrap>:241: RuntimeWarning: nanobind: type 'QuadratureType' was already registered!
0.410 
0.411 <frozen importlib._bootstrap>:241: RuntimeWarning: nanobind: type 'CellType' was already registered!
0.411 
0.411 <frozen importlib._bootstrap>:241: RuntimeWarning: nanobind: type 'ElementFamily' was already registered!
0.411 
0.411 <frozen importlib._bootstrap>:241: RuntimeWarning: nanobind: type 'FiniteElement' was already registered!
0.411 
0.412 <frozen importlib._bootstrap>:241: RuntimeWarning: nanobind: type 'LagrangeVariant' was already registered!
0.412 
0.412 <frozen importlib._bootstrap>:241: RuntimeWarning: nanobind: type 'DPCVariant' was already registered!
0.412 
0.412 <frozen importlib._bootstrap>:241: RuntimeWarning: nanobind: type 'PolysetType' was already registered!
0.412 
0.413 Traceback (most recent call last):
0.413   File "<string>", line 1, in <module>
0.414   File "/src/basix/python/basix/__init__.py", line 7, in <module>
0.414     from . import cell, finite_element, lattice, polynomials, quadrature, sobolev_spaces, variants
0.414   File "/src/basix/python/basix/finite_element.py", line 3, in <module>
0.415     from ._basixcpp import ElementFamily as _EF
0.415 ImportError: cannot import name 'ElementFamily' from 'basix.finite_element._basixcpp' (/usr/lib/python3/dist-packages/basix/_basixcpp.cpython-310-x86_64-linux-gnu.so)
0.419 free(): invalid pointer
0.507 Aborted (core dumped)
------
```

2023-10-27 14:24 UTC, francesco-ballarin commented
> I'm not sure what the cause of the issue is, but if you don't use build-isolation, you get the following error when import basix:

I guess that my question is more: how come that `pip install .` (without `-e`) works correctly?

2023-10-27 19:53 UTC, jhale commented
@francesco-ballarin It is a bug in scikit-build-core latest version for editable builds that will be fixed upstream at some point.

2023-10-27 20:02 UTC, jorgensd commented
> @francesco-ballarin It is a bug in scikit-build-core latest version for editable builds that will be fixed upstream at some point.

Note that even pining scikit-build-core doesn’t help wrt removing build isolation. So there are two scikit bugs here:
1. Need build isolation for editable install 
2. https://github.com/scikit-build/scikit-build-core/issues/532

2023-10-28 10:58 UTC, jorgensd commented
A compromise would be to use split install in one of the CIs, as it would then be easily maintainable and easily accessed by developers.

2023-10-30 11:22 UTC, mscroggs commented
> split install

I think that [this run](https://github.com/FEniCS/basix/blob/3b4cf17b574c0f181f539daaa8b4be099ccae0c7/.github/workflows/pythonapp.yml#L143-L183) on the CI is trying to do this, but perhaps needs updating? Or do you mean something else by split install?

2023-10-30 11:57 UTC, jorgensd commented
> > split install
> 
> I think that [this run](https://github.com/FEniCS/basix/blob/3b4cf17b574c0f181f539daaa8b4be099ccae0c7/.github/workflows/pythonapp.yml#L143-L183) on the CI is trying to do this, but perhaps needs updating? Or do you mean something else by split install?

It does a split install, but not a split editable installation. Most developers would probably use the editable install option (which has the requirements described above).

2023-10-30 11:58 UTC, mscroggs commented
> > > split install
> > 
> > 
> > I think that [this run](https://github.com/FEniCS/basix/blob/3b4cf17b574c0f181f539daaa8b4be099ccae0c7/.github/workflows/pythonapp.yml#L143-L183) on the CI is trying to do this, but perhaps needs updating? Or do you mean something else by split install?
> 
> It does a split install, but not a split editable installation. Most developers would probably use the editable install option (which has the requirements described above).

We change it to editable. Or include both (is there any benefit to having both?)

2023-10-30 12:08 UTC, jorgensd commented
> > > > split install
> > > 
> > > 
> > > I think that [this run](https://github.com/FEniCS/basix/blob/3b4cf17b574c0f181f539daaa8b4be099ccae0c7/.github/workflows/pythonapp.yml#L143-L183) on the CI is trying to do this, but perhaps needs updating? Or do you mean something else by split install?
> > 
> > 
> > It does a split install, but not a split editable installation. Most developers would probably use the editable install option (which has the requirements described above).
> 
> We change it to editable. Or include both (is there any benefit to having both?)

Well, it would give better coverage. In any case, we would need the build_requirements.txt to be Added to Basix.

2023-10-30 15:20 UTC, garth-wells requested changes

2023-10-30 15:20 UTC, garth-wells commented on python/README.rst
> +This document explains how to install the Basix Python interface, given that the C++ interface has been built.
Shorten text.

2023-10-30 15:20 UTC, garth-wells commented on python/build-requirements.txt
See earlier version comments.

2023-10-30 15:20 UTC, garth-wells commented on python/README.rst
> +     python3 -m pip -v install -r build-requirements.txt
Use `pip` (shorter) and no need for `-v`.

2023-10-30 15:20 UTC, garth-wells commented on python/README.rst
> +    python3 -m pip -v install --no-build-isolation .
See above comments.

2023-11-07 18:15 UTC, garth-wells commented
Closing this as the editable issue was fixed by #727. Can be re-opened with any refinements of the docs.

2023-11-07 18:15 UTC, closed without merging